[workspace]
members = [
    "zero2prod",
    "chapter-10",
    "chapter-13",
    "chapter-15",
    "chapter-16",
    "chapter-17",
    "chapter-18",
    "chapter-19",
    "chapter-20",
    "microsoft_learning/hello_world",
    "my-redis"
]